### PR TITLE
I made easy to switch on/off of this script.

### PR DESCRIPTION
**Pull request by shadero**
You can use it when access to google currently.
(Implementation is quite crude! sorry!)

### CODE REVIEW

**Review by yanorei32 — CHANGES_REQUESTED** [review]
Please change google.com to soundcloud.com

**Comment by yanorei32** [comment]
LGTM!

**Comment by yanorei32** [comment]
You did it! You created a perfect regex pattern!
It's a popular security issue and you fixed!

**Comment by shadero** [comment]
Sorry...

**Pull request merged**
